repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.25.0'
    hooks:
    -   id: eslint
        args: [--config eslint.config.js]
        additional_dependencies:
          - eslint@9.25.0
          - eslint-plugin-vue@10.0.0
          # Add these:
          - '@typescript-eslint/eslint-plugin' # Add the specific version you use locally
          - '@typescript-eslint/parser'       # Add the specific version you use locally
          - 'vue-eslint-parser'               # Add the specific version you use locally
          # You probably don't need this one if using the flat config above:
          # - '@vue/eslint-config-typescript@14.5.0'
          - typescript@5.8.3

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.18.0
    hooks:
      - id: stylelint
        files: \.(scss|vue)$
        args: [--fix, --config=.stylelintrc.json]
        additional_dependencies:
          - stylelint@16.18.0
          - stylelint-config-standard-scss@14.0.0
          - stylelint-config-recommended-vue@1.6.0
          - postcss@8.5.3
          - postcss-html@1.8.0
