/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AfricanCountries: typeof import('./src/components/AfricanCountries.vue')['default']
    FrenchDepartments: typeof import('./src/components/FrenchDepartments.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsStates: typeof import('./src/components/UsStates.vue')['default']
  }
}
