/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AfricanCountries: typeof import('./src/components/WorldCountries/AfricanCountries.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AsiaMapGame: typeof import('./src/components/WorldCountries/AsiaMapGame.vue')['default']
    AustralianStates: typeof import('./src/components/AdministrativeDivisions/AustralianStates.vue')['default']
    BelgianProvinces: typeof import('./src/components/AdministrativeDivisions/BelgianProvinces.vue')['default']
    BrazilianStates: typeof import('./src/components/AdministrativeDivisions/BrazilianStates.vue')['default']
    CanadianProvinces: typeof import('./src/components/AdministrativeDivisions/CanadianProvinces.vue')['default']
    CapitalGame: typeof import('./src/components/CapitalGame.vue')['default']
    ChineseProvinces: typeof import('./src/components/AdministrativeDivisions/ChineseProvinces.vue')['default']
    DutchProvinces: typeof import('./src/components/AdministrativeDivisions/DutchProvinces.vue')['default']
    EuropeMapGame: typeof import('./src/components/WorldCountries/EuropeMapGame.vue')['default']
    FlagGame: typeof import('./src/components/FlagGame.vue')['default']
    FrenchDepartments: typeof import('./src/components/AdministrativeDivisions/FrenchDepartments.vue')['default']
    GameHub: typeof import('./src/components/GameHub.vue')['default']
    GermanStates: typeof import('./src/components/AdministrativeDivisions/GermanStates.vue')['default']
    GoogleLoginButton: typeof import('./src/components/auth/GoogleLoginButton.vue')['default']
    ItalianRegions: typeof import('./src/components/AdministrativeDivisions/ItalianRegions.vue')['default']
    LoginDropdown: typeof import('./src/components/auth/LoginDropdown.vue')['default']
    MapGame: typeof import('./src/components/MapGame.vue')['default']
    NorthAmericaMapGame: typeof import('./src/components/WorldCountries/NorthAmericaMapGame.vue')['default']
    OceaniaMapGame: typeof import('./src/components/WorldCountries/OceaniaMapGame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RussianOblasts: typeof import('./src/components/AdministrativeDivisions/RussianOblasts.vue')['default']
    SouthAmericaMapGame: typeof import('./src/components/WorldCountries/SouthAmericaMapGame.vue')['default']
    SpanishCommunities: typeof import('./src/components/AdministrativeDivisions/SpanishCommunities.vue')['default']
    UkCounties: typeof import('./src/components/AdministrativeDivisions/UkCounties.vue')['default']
    UkrainianOblasts: typeof import('./src/components/AdministrativeDivisions/UkrainianOblasts.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    UsStates: typeof import('./src/components/AdministrativeDivisions/UsStates.vue')['default']
    WorldCountries: typeof import('./src/components/WorldCountries/WorldCountries.vue')['default']
  }
}
