[build]
command = "bun run build" # or your actual build command
publish = "dist"          # or your actual output directory

[[headers]]
for = "/geography-game/assets/*.js"
[headers.values]
Content-Type = "application/javascript"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/geography-game/assets/index-*.js"
[headers.values]
Content-Type = "application/javascript"
X-Content-Type-Options = "nosniff"
