[[headers]]
for = "/geography-game/assets/*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
# This is a catch-all for any JS files
for = "/*.js"
[headers.values]
Content-Type = "application/javascript"
