name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write # Added permission for commenting on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Building PR with base: /geography-game/${{ github.head_ref }}/"
          GITHUB_HEAD_REF=${{ github.head_ref }} bun run build
        env:
          BASE_URL: /geography-game/${{ github.head_ref }}/

      - name: Build for main
        if: github.event_name != 'pull_request'
        run: |
          echo "Building main with base: /geography-game/"
          bun run build
        env:
          BASE_URL: /geography-game/

      # For main branch - use GitHub Pages deployment
      - name: Upload artifact
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # For PR branches - deploy to gh-pages branch in subdirectory
      - name: Deploy PR Preview
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: ${{ github.head_ref }}
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.issue.number;
            const branch = context.payload.pull_request.head.ref;

            const previewUrl = `https://${owner}.github.io/geography-game/${branch}/`;

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `## 🚀 Preview Deployment\n\n**Preview URL:** [${previewUrl}](${previewUrl})\n\nThis preview will update automatically when new changes are pushed to this PR.`
            });
  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
