name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Building PR with base: /geography-game/${{ github.head_ref }}/"
          bun run build
        env:
          BASE_URL: /geography-game/${{ github.head_ref }}/

      - name: Build for main
        if: github.event_name != 'pull_request'
        run: |
          echo "Building main with base: /geography-game/"
          bun run build
        env:
          BASE_URL: /geography-game/

      # Debug: List build output
      - name: List build output
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of assets (if exists):"
          ls -la dist/assets/ || echo "No assets directory found"

      # For PR branches - deploy to gh-pages branch in subdirectory
      - name: Deploy PR Preview
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: ${{ github.head_ref }}
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false # Important! Don't remove other directories

      # For main branch - also deploy to gh-pages but in the root
      - name: Deploy Main to Root
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean-exclude: |
            */

      # Add a comment to the PR with the preview URL
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.issue.number;
            const branch = context.payload.pull_request.head.ref;

            const previewUrl = `https://${owner}.github.io/geography-game/${branch}/`;

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `## 🚀 Preview Deployment\n\n**Preview URL:** [${previewUrl}](${previewUrl})\n\nThis preview will update automatically when new changes are pushed to this PR.`
            });
